export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const GET_USER_LOGIN = "GET_USER_LOGIN"
export const GET_USER_LOGIN_DATA = "GET_USER_LOGIN_DATA"

export const LOGOUT = "LOGOUT"

export const SPV_DATA_REQUEST = "SPV_DATA_REQUEST"

export const SPV_CREATE_USER = "SPV_CREATE_USER"
export const SPV_GET_PROJECT = "SPV_GET_PROJECT"

export const SPV_COLUMN_DATA = "SPV_COLUMN_DATA"

export const SPV_UPDATE_STATUS = "SPV_UPDATE_STATUS"


export const PLANNER_COLUMN_DATA = "PLANNER_COLUMN_DATA"
export const PLANNER_CREATE_PROJECT = "PLANNER_CREATE_PROJECT"
export const PLANNER_CREATE_TASK = "PLANNER_CREATE_TASK"


export const PLANNER_DATA_REQUEST = "PLANNER_DATA_REQUEST"
export const PLANNER_DATA_SUCCESS = "PLANNER_DATA_SUCCESS"
export const PLANNER_DATA_FAILED = "PLANNER_DATA_FAILED"

export const WORKER_DATA_REQUEST = "WORKER_DATA_REQUEST"
export const WORKER_DATA_SUCCESS = "WORKER_DATA_SUCCESS"
export const WORKER_DATA_FAILED = "WORKER_DATA_FAILED"

export const CREATE_USER_PLANNER = "CREATE_USER_PLANNER"
export const EDIT_USER_PLANNER = "EDIT_USER_PLANNER"
export const DELETE_USER_PLANNER = "DELETE_USER_PLANNER"

export const CREATE_USER_WORKER = "CREATE_USER_WORKER"
export const EDIT_USER_WORKER = "EDIT_USER_WORKER"
export const DELETE_USER_WORKER = "DELETE_USER_WORKER"

