export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const GET_USER_LOGIN = "GET_USER_LOGIN"
export const GET_USER_LOGIN_DATA = "GET_USER_LOGIN_DATA"

export const LOGOUT = "LOGOUT"

export const SPV_DATA_REQUEST = "SPV_DATA_REQUEST"
export const SPV_DATA_SUCCESS = "SPV_DATA_SUCCESS"
export const SPV_DATA_FAILED = "SPV_DATA_FAILED"

export const PLANNER_DATA_REQUEST = "PLANNER_DATA_REQUEST"
export const PLANNER_DATA_SUCCESS = "PLANNER_DATA_SUCCESS"
export const PLANNER_DATA_FAILED = "PLANNER_DATA_FAILED"

export const WORKER_DATA_REQUEST = "WORKER_DATA_REQUEST"
export const WORKER_DATA_SUCCESS = "WORKER_DATA_SUCCESS"
export const WORKER_DATA_FAILED = "WORKER_DATA_FAILED"

export const CREATE_USER_PLANNER = "CREATE_USER_PLANNER"
export const EDIT_USER_PLANNER = "EDIT_USER_PLANNER"
export const DELETE_USER_PLANNER = "DELETE_USER_PLANNER"

export const CREATE_USER_WORKER = "CREATE_USER_WORKER"
export const EDIT_USER_WORKER = "EDIT_USER_WORKER"
export const DELETE_USER_WORKER = "DELETE_USER_WORKER"

